on:
  workflow_dispatch:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    timeout-minutes: 60
    environment: normal
    steps:
    - name: Checkout the code
      uses: actions/checkout@master
    - name: Build frontend
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - run: npm install
      working-directory: frontend/game-qube        
    - run: npm run build
      working-directory: frontend/game-qube
    - name: Deploy to Fly.io 
      uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
