on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    timeout-minutes: 60
    steps:
    - name: Checkout the code
      uses: actions/checkout@master
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      with:
        build-root-directory: ./backend/game-qube
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build -Dquarkus.package.type=native
        build-root-directory: ./backend/game-qube
